import React, { Component } from "react";
import "./../../styles/Table.css";

export default class SudokuTable extends Component {
  render() {
    return (
      <table className="SudokuTable">
        <tr>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
        </tr>
        <tr>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
        </tr>
        <tr>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
          <th>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
            </tr>
            <tr>
              <th>4</th>
              <th>5</th>
              <th>6</th>
            </tr>
            <tr>
              <th>7</th>
              <th>8</th>
              <th>9</th>
            </tr>
          </th>
        </tr>
      </table>
    );
  }
}
